version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/myapp
    networks:
     - dns
  redis:
    image: redis
    networks:
     - dns
    
networks:
  dns:
    external: true
